batch_size: 128
device: cuda
eval_interval: 30
lr: 0.0013
model_config:
  dropout: 0.
  seq_len: 150
  d_model: 512
  nhead: 8
  num_layers: 6
  ffn_dim: 2048
model_name: TokenTransformer
num_workers: 8
sample_duration: 2
save: false
seq_len: 150
split_train_set: 0.1
steps: 1000
train_dataset_path: /runpod-volume/encodec_latents/poly_async_power
warmup_fraction: 0.03
weight_decay: 0.01
